import json
import uuid
from agents.agent_orchestrator import graph_compilation
from core.redis import RedisCache
from models.api_models import AgentRequest, AgentResponse

from utils.logger import logger

async def run_agent_logic(payload: AgentRequest) -> AgentResponse:
    logger.debug(f"Running agent with query='{payload.query}', session_id='{payload.session_id}'")
    redis = RedisCache()
    
    try:
        session_id = payload.session_id or str(uuid.uuid4())

        # TODO: fetch history from cache if required based on session_id
        stateKey = redis.get_stateKey(session_id)
        chat_history = ""
        if await redis.exists(stateKey):
            logger.debug(f"Fetching chat history for session_id={session_id}")
            chat_history = await redis.get(stateKey)
            state = json.loads(chat_history)
        else:
            state = {
                "messages": [],
                "intent": None,
                "final_response": None
             }

        state["messages"].append({
            "role": "user",
            "content": payload.query
        })

        app_graph = graph_compilation()
        # TODO: call the agent and process the query

        for updated_state in app_graph.stream(state):
            pass
       
        result = updated_state.get("finalResponse", "")
        if not result:
            result = "No response generated by the agent."
        logger.debug(f"Agent response for session_id={session_id}: {result}")

        # Save updated state back to Redis
        await redis.set(stateKey, json.dumps(updated_state))  # Set TTL to 1 hour

        return AgentResponse(
            response=result,
            session_id=session_id,
            status_code=200,
        )

    except Exception as e:
        logger.exception("Agent processing failed")
        return AgentResponse(
            response="",
            session_id=payload.session_id or "unknown",
            error=str(e),
            status_code=500,
        )
