# Main agent class containing the logic of running complete flow

import json
import re
from typing import Annotated, TypedDict
from fastapi import logger
from langchain_core.messages import HumanMessage, AIMessage , AnyMessage
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph, END
from pydantic import BaseModel
from utils.logger import logger
from agents.Drug_Analysis.main import MedicalChatbot
from agents.Intent_Analysis.intent_analysis import IntentIdentifier
from agents.Medical_Analysis.Medical_rag import MedicalAgent
from agents.ResponderAgent.responderAgent import ResponsderAgent
from agents.Utils.common_methods import extract_image_info

class AgentState(TypedDict):
    messages: Annotated[list[AnyMessage], add_messages]
    finalResponse : str = "NOne"
    agent_intent : str = "NOne"
    intent_response: str = "None"
# Agents Method 


def intentAgent(state: AgentState):
    print(f"IntentAgent Initial state {state}")
    last_msg = state['messages'][-1].content
    print(f"Last message for the Intent agent {last_msg}")
    agentIntent = IntentIdentifier(state)
    intent_response = agentIntent.get_intent_agent_response(last_msg)[1]
    logger.info(f"Intent agent Response : {intent_response}")
    pattern = r'\{.*?\}'
    match = re.search(pattern,intent_response, re.DOTALL)
    if match:
        json_str = match.group()
        intent_result = json.loads(json_str)
    logger.info(f"Final result of intent {intent_result}")
    intent = intent_result['actual_tag']
    response = intent_result['response']
    return {**state , "agent_intent" : intent, "intent_response": response}
    
    
def disease_agent(state: AgentState):
    query = state['messages'][-1].content
    diseaseAgent = MedicalChatbot(chat_history=state)
    disease_response = diseaseAgent.process_user_message(query)[0]
    logger.info(f"Disease Analysis Agent Response {disease_response}")
    # state["messages"] = AIMessage(content=disease_response)
    return {**state, "finalResponse": disease_response}


def drugs_agent(state: AgentState):
    query = state['messages'][-1].content
    image_info = extract_image_info(query)
    drugsAgent = MedicalAgent()
    drugs_response = drugsAgent.get_responder_output(isImage=image_info.get("isImage"), image_source=image_info.get("imageSource"), query=query)
    # state["messages"] = AIMessage(content=drugs_response)
    return {**state, "finalResponse": drugs_response}

def responder_agent(state: AgentState):
    query = state['messages'][-1].content
    intent = state['agent_intent']
    finalResponse = state.get('finalResponse', state.get('intent_response', "No response generated by the agent."))
    responder_agent = ResponsderAgent(chat_history=state)
    responder_agent_response = responder_agent.get_responder_output(user_query=query, intent=intent , final_response=finalResponse)
    logger.info(f"Following is the response of responder agent {responder_agent_response}")
    state["messages"].append({"role" : "assistant" , "content" : responder_agent_response})
    return {**state , "finalResponse" : responder_agent_response}

def intent_condition(state : AgentState):
    return state["agent_intent"]

def graph_compilation():
    graph = StateGraph(AgentState)
    graph.add_node("intent", intentAgent)
    graph.add_node("disease_agent", disease_agent)
    graph.add_node("drug_agent", drugs_agent)
    graph.add_node("responder_agent", responder_agent)

    graph.set_entry_point("intent")
    graph.add_conditional_edges("intent",intent_condition, {
        "disease_and_symptom_analyzer": "disease_agent",
        "drugs_analyser": "drug_agent",
        "small_talk" : "responder_agent"
    })
    graph.add_edge("disease_agent", "responder_agent")
    graph.add_edge("drug_agent", "responder_agent")
    graph.set_finish_point("responder_agent")
    app_graph = graph.compile()
    return app_graph